package com.multimerchant_haze.rest.v1.modules.payments.model;

import com.multimerchant_haze.rest.v1.modules.users.producer.model.ProducerHasPaymentMethod;
import com.multimerchant_haze.rest.v1.modules.payments.dto.PaymentMethodDTO;
import com.multimerchant_haze.rest.v1.modules.payments.model.payment_types_model.Payment;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Created by zorzis on 9/7/2017.
 */
@Entity
@Table(name = "payment_methods")
public class PaymentMethod implements Serializable
{

        @Id
        @Column(name = "paymentMethodID")
        private String paymentMethodID;

        @Column(name = "paymentMethodName", nullable = false)
        private String paymentMethodName;

        @Column(name = "paymentMethodDescription", nullable = false)
        private String paymentMethodDescription;

        @OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
        private Set<ProducerHasPaymentMethod> producerHasPaymentMethodSet = new HashSet<>(0);


        @OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
        private Set<Payment> payment;



        public PaymentMethod()
        {

        }

        public PaymentMethod(PaymentMethodDTO paymentMethodDTO)
        {
                this.paymentMethodID = paymentMethodDTO.getPaymentMethodID();
                this.paymentMethodName = paymentMethodDTO.getPaymentMethodName();
                this.paymentMethodDescription = paymentMethodDTO.getPaymentMethodDescription();
        }


        public String getPaymentMethodID()
        {
                return paymentMethodID;
        }

        public void setPaymentMethodID(String paymentMethodID)
        {
                this.paymentMethodID = paymentMethodID;
        }

        public String getPaymentMethodName()
        {
                return paymentMethodName;
        }

        public void setPaymentMethodName(String paymentMethodName)
        {
                this.paymentMethodName = paymentMethodName;
        }

        public String getPaymentMethodDescription()
        {
                return paymentMethodDescription;
        }

        public void setPaymentMethodDescription(String paymentMethodDescription)
        {
                this.paymentMethodDescription = paymentMethodDescription;
        }

        public Set<ProducerHasPaymentMethod> getProducerHasPaymentMethodSet()
        {
                return producerHasPaymentMethodSet;
        }

        public void setProducerHasPaymentMethodSet(Set<ProducerHasPaymentMethod> producerHasPaymentMethodSet)
        {
                this.producerHasPaymentMethodSet = producerHasPaymentMethodSet;
        }

        public Set<Payment> getPayment()
        {
                return payment;
        }

        public void setPayment(Set<Payment> payment)
        {
                this.payment = payment;
        }


        @Override
        public String toString()
        {
                StringBuilder sb = new StringBuilder();
                sb.append("PaymentMethod: ");
                sb.append("[");
                sb.append("Autogenerated MySQL id: ");
                sb.append(this.paymentMethodID);
                sb.append(" | ");
                sb.append("Payment Method Name: ");
                sb.append(this.paymentMethodName);
                sb.append(" | ");
                sb.append("Payment Method Description: ");
                sb.append(this.paymentMethodDescription);
                sb.append("]");
                return sb.toString();
        }

}


